name: fullwidth_halfwidth_converter
description: Package to provide conversion between fullwidth and halfwidth in Japanese.
version: 1.0.2
repository: https://github.com/hygehyge/fullwidth_halfwidth_converter

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  benchmark_runner: ^2.0.1
  test: ^1.26.2
  flutter_lints: ^6.0.0